quarkus.http.test-port=0
quarkus.rest-client.client-prefix.connect-timeout=30000

ucsc-genome-api/mp-rest/url=https://api.genome.ucsc.edu
hgnc-api/mp-rest/url=https://rest.genenames.org
blat-api/mp-rest/url=https://genome.ucsc.edu
tfbind-api/mp-rest/url=https://tfbind.hgc.jp/cgi-bin/calculate.cgi
uniprot-api/mp-rest/url=https://rest.uniprot.org
pdbe-api/mp-rest/url=https://www.ebi.ac.uk/pdbe/graph-api