quarkus.http.test-port=0
quarkus.rest-client.client-prefix.connect-timeout=30000

quarkus.mongodb.connection-string=${DB_URL:mongodb://localhost:27017}
quarkus.mongodb.credentials.username=${DB_USER}
quarkus.mongodb.credentials.password=${DB_PASSWORD}
quarkus.mongodb.database=${DB_NAME}
quarkus.mongodb.credentials.auth-source=admin
quarkus.http.port=${PORT:8080}

mp.fault.tolerance.global.Retry/maxRetries=5
mp.fault.tolerance.global.Retry/delay=1000

ontologies-api/mp-rest/url=${ONTOLOGIES:http://ontologies:8080}
config-and-control-api/mp-rest/url=${CONFIG-AND-CONTROL:http://config-and-control:8080}

ucsc-genome-api/mp-rest/url=https://api.genome.ucsc.edu
hgnc-api/mp-rest/url=https://rest.genenames.org
blat-api/mp-rest/url=https://genome.ucsc.edu
uniprot-api/mp-rest/url=https://rest.uniprot.org
tfbind-api/mp-rest/url=https://tfbind.hgc.jp/cgi-bin/calculate.cgi
pdbe-api/mp-rest/url=https://www.ebi.ac.uk/pdbe
pubmed-integration-api/mp-rest/url=${PUBMED-INTEGRATION:http://pubmed-integration:8080}
