quarkus.http.test-port=0
quarkus.rest-client.client-prefix.connect-timeout=30000

quarkus.mongodb.connection-string=${DB_URL:mongodb://localhost:27017}

quarkus.mongodb.credentials.username=${DB_USER}
quarkus.mongodb.credentials.password=${DB_PASSWORD}
quarkus.mongodb.database=${DB_NAME}
quarkus.mongodb.credentials.auth-source=admin

ucsc-genome-api/mp-rest/url=https://api.genome.ucsc.edu
hgnc-api/mp-rest/url=https://rest.genenames.org
blat-api/mp-rest/url=https://genome.ucsc.edu
tfbind-api/mp-rest/url=https://tfbind.hgc.jp/cgi-bin/calculate.cgi
uniprot-api/mp-rest/url=https://rest.uniprot.org
pdbe-api/mp-rest/url=https://www.ebi.ac.uk/pdbe/graph-api
ontologies-api/mp-rest/url=http://ontologies:8080