pipeline{
    agent any
    stages{
        stage('Test'){
              agent {
                  docker {
                      image 'jelastic/maven:3.9.5-openjdk-21'
                      args '-v /root/.m2:/root/.m2'
                  }
              }
              steps{
                   sh 'mvn test'
              }
        }

    }
}